
### Inicio
GET http://localhost:3000/


### crear pedido
POST http://localhost:3000/orders-service
Content-Type: application/json

{
"nombre": "Leche Entera",
"categoria": "Alimentos",
"precio" : 5000,
"cantidad" :3
}


### leer el pedido
GET http://localhost:3000/orders-retriever-service

### borrar pedido
DELETE http://localhost:3000/orders-updater-service/order:1731458931948

### pedido actualizado por id
PUT http://localhost:3000/orders-updater-service/order:1731459673693
Content-Type: application/json

{
"nombre": "Leche Entera",
"categoria": "Alimentos",
"precio" : 7000,
"cantidad" :3
}